name = "MyTest2"
uuid = "895ad2d6-3e07-4d64-b171-09bf5b9500d8"
authors = ["Henrik Foss Jørgensen"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
